### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by arthurbailao** [arthurbailao/aws-kcl#2]
i need to write some tests

**Comment by arthurbailao** [comment]
[reference](https://github.com/awslabs/amazon-kinesis-client-nodejs/blob/master/test/kcl/kcl_process_tests.js) from nodejs client

**Comment by VinGarcia** [comment]
@arthurbailao, I started writing some tests for the readMessage function and I got an unexpected behavior, it seems that if it receives a json message spread among multiple lines it will only read the first line.

However, by reading the function code (that read lines from the input until there is no more data to read) I got the impression that it was expected to work with this type of json.

For now I will only test with single-line json inputs, but in future I can think of 2 solutions:
1. If we want only to parse single line JSONs we should remove the `for { ... }` from inside the function.
2. If we want to accept multi-line JSONs we should understand better what criteria we should use to denote the end of a message.
